In [51]:

# Importing libraries
import numpy as np
import pandas as pd
from scipy.stats import mode
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
 
%matplotlib inline

In [54]:
# Reading the train.csv by removing the
# last column since it's an empty column
DATA_PATH = "Training.csv"
data = pd.read_csv(DATA_PATH).dropna(axis = 1)

# Checking whether the dataset is balanced or not
disease_counts = data["prognosis"].value_counts()
temp_df = pd.DataFrame({
	"Disease": disease_counts.index,
	"Counts": disease_counts.values
})

plt.figure(figsize = (18,8))
sns.barplot(x = "Disease", y = "Counts", data = temp_df)
plt.xticks(rotation=90)
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'Training.csv'

In [24]:
print(x)

[['itching' ' skin_rash' ' nodal_skin_eruptions' ... nan nan nan]
 [' skin_rash' ' nodal_skin_eruptions' ' dischromic _patches' ... nan nan
  nan]
 ['itching' ' nodal_skin_eruptions' ' dischromic _patches' ... nan nan
  nan]
 ...
 [' burning_micturition' ' bladder_discomfort' ' foul_smell_of urine' ...
  nan nan nan]
 [' skin_rash' ' joint_pain' ' skin_peeling' ... nan nan nan]
 [' skin_rash' ' high_fever' ' blister' ... nan nan nan]]


In [26]:
print(y)

['Fungal infection' 'Fungal infection' 'Fungal infection' ...
 'Urinary tract infection' 'Psoriasis' 'Impetigo']


In [27]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data

encoder = OneHotEncoder(sparse=False)
# transform data
x = encoder.fit_transform(x)

In [40]:
print(
    f"The encoded dataset contains {x.shape[1]} features")

The encoded dataset contains 408 features


In [29]:
print(x)

[[0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]]


In [30]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y=le.fit_transform(y)

In [31]:
print(y)

[15 15 15 ... 38 35 27]


In [32]:
# spliting dataset into test and training set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [33]:
# feature scaling 
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.fit_transform(x_test)

In [34]:
# train the logistic regression model on the training set
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)  

KNeighborsClassifier()

In [50]:
# predicting a new result
prid=[[' skin_rash' ,' nodal_skin_eruptions' ,' dischromic _patches','nan','nan','nan','nan','nan','nan','nan','nan','nan','nan'
,'nan','nan','nan','nan']]
prid = encoder.fit_transform(prid)
print(prid)
classifier.predict(ss.transform(prid)) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


ValueError: X has 17 features, but StandardScaler is expecting 408 features as input.

In [35]:
# predicting test set result
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[18 18]
 [40 40]
 [36 36]
 ...
 [40 40]
 [17 17]
 [ 4  4]]


In [36]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

# 64 correct predictions who didn't buy product
# 29 correct predictions who did buy product
# 4 incorrect predictions who didn't buy product
# 3 incorrect predictions who did buy product

[[21  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 34 ...  0  0  0]
 ...
 [ 0  0  0 ... 28  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 33]]


1.0

In [37]:
# save the model to disk
import joblib
filename = 'finalized_model.sav'

joblib.dump(classifier, filename)
 


['finalized_model.sav']

In [49]:
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(x_test, y_test)
print(result)

1.0
